### ISSUE TITLE
Exceptie disconnect

### ISSUE THREAD

**Issue by Regy1K** [RaduC1234/tClient-Server#4]
java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.SocketChannelImpl.ensureOpenAndConnected(SocketChannelImpl.java:180)
	at java.base/sun.nio.ch.SocketChannelImpl.beginRead(SocketChannelImpl.java:312)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:347)
	at team.JavaTeens.Server.ServerInstance.handleIncomingBytes(ServerInstance.java:129)
	at team.JavaTeens.Server.ServerInstance.handleClientConnection(ServerInstance.java:104)
	at team.JavaTeens.Server.ServerInstance.run(ServerInstance.java:78)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by RaduC1234** [comment]
Done
